# Generated by Django 4.0 on 2021-12-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_id_alter_usersettings_id_voting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votefact',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
