# Generated by Django 4.0 on 2022-01-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_votefact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='title',
            field=models.CharField(default='DEFINE ME!', max_length=255),
            preserve_default=False,
        ),
    ]
