# Generated by Django 4.0 on 2022-01-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_votefactvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votefact',
            name='variant',
        ),
    ]
