# Generated by Django 4.0.2 on 2022-02-17 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categorycharacteristic_comparingreview_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparingreview',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
