# Generated by Django 4.0.2 on 2022-03-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comparingreview_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycharacteristic',
            name='comparator',
            field=models.IntegerField(choices=[(0, 'Меньше - лучше'), (1, 'Больше - лучше'), (2, 'По рейтингу')], default=0),
        ),
        migrations.AlterField(
            model_name='categorycharacteristic',
            name='value_type',
            field=models.IntegerField(choices=[(0, 'Целое число'), (1, 'Вещественное число'), (2, 'Логическое значение'), (3, 'Строка')], default=0),
        ),
        migrations.CreateModel(
            name='CategoryStringCharacteristicRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3000)),
                ('rating', models.IntegerField()),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorycharacteristic')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categorystringcharacteristicrating',
            constraint=models.UniqueConstraint(fields=('characteristic', 'rating'), name='unique_votefact'),
        ),
    ]
