# Generated by Django 4.0.2 on 2022-03-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_categorycharacteristic_comparator_and_more'),
        ('main', '0009_remove_user_avatar_useravatar'),
    ]

    operations = [
    ]
