# Generated by Django 4.0.2 on 2022-03-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20220303_1955'),
        ('main', '0011_alter_product_color'),
    ]

    operations = [
    ]
