# Generated by Django 4.0.2 on 2022-03-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merge_20220324_1946'),
        ('main', '0012_merge_20220324_1952'),
    ]

    operations = [
    ]
