# Generated by Django 4.0.2 on 2022-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_product_auditory_product_auditory_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
