# Generated by Django 4.0.2 on 2022-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_product_auditory_alter_product_auditory_friday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
