# Generated by Django 4.0.2 on 2022-09-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_calchistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calchistory',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='first',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='result',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calchistory',
            name='second',
            field=models.IntegerField(default=None),
        ),
    ]
